### ISSUE TITLE
Japanese and Korean styles

### ISSUE THREAD

**Issue by xfq** [w3c/predefined-counter-styles#39]
It seems that the [Japanese (Hiragana/Katakana)](https://w3c.github.io/predefined-counter-styles/#kana-styles) and [Korean (Hangul)](https://w3c.github.io/predefined-counter-styles/#korean-styles) sections also include counter styles in Kanji/Hanja, such as the [japanese-informal](https://w3c.github.io/predefined-counter-styles/#japanese-informal) and [korean-hanja-informal](https://w3c.github.io/predefined-counter-styles/#korean-hanja-informal) counter styles. IMHO it is better to add them to the [Han CJK](https://w3c.github.io/predefined-counter-styles/#chinese-styles) section or change the name of these sections (because they not only contain Hiragana/Katakana and Hangul).

**Comment by r12a** [comment]
Ah, thanks for spotting that. I forgot to change the headings.  I moved the ideographic styles OUT of the Han CJK section (because i kept looking for Japanese or Korean styles, and having to remember that there were also some in the ideographic section.  Much easier to find things in the new arrangement, because one tends to look for styles to fit a given language, then decide on what type of characters, rather than the other way around.) 

I'll fix this on Tuesday.

**Comment by r12a** [comment]
Fixed by https://github.com/w3c/predefined-counter-styles/pull/41
