### ISSUE TITLE
‘fullwidth-’, ‘circled-’ and similar styles

### ISSUE THREAD

**Issue by Crissov** [w3c/predefined-counter-styles#6]
- [Latin](http://w3c.github.io/predefined-counter-styles/#latin-styles)
- [European Digits & Roman](http://w3c.github.io/predefined-counter-styles/#digit-styles)

The simple styles that use roman letters or international digits inside an em-square have `fullwidth` in their name.
- `fullwidth-lower-alpha`
- `fullwidth-upper-alpha`
- `fullwidth-decimal`
- `fullwidth-lower-roman`
- `fullwidth-upper-roman`

Counter styles with precomposed circles, parentheses or dots without using `suffix:` do not have the `fullwidth-` prefix.
- `circled-decimal`
- `circled-lower-latin`
- `circled-upper-latin`
- `dotted-decimal`
- `double-circled-decimal`
- `filled-circled-decimal`
- `parenthesized-decimal`

As far as I know, Unicode inherited theses characters from legacy East Asian character sets/encodings primarily for round-trip compatibility with existing content. For authors who are not familiar with the history of character encodings, `fullwidth` is completely opaque and meaningless. That’s most of them, at least outside China, Japan and Korea. Yet, Europeans, Africans or Americans used only to the roman script might still feel tempted to use these counter styles. 
1. Should they be specified at all?
2. Should we find a better prefix (or reuse `cjk-`) and apply it consistently? 
3. Should they be in a common section?
   - … a new, separate one?
   - … part of [Han Ideographic (Chinese/Japanese/Korean)](http://w3c.github.io/predefined-counter-styles/#chinese-styles)?

I believe the circled ones are okay, the rest should not be used, at least not in Western texts.

**Comment by r12a** [comment]
1. They are used for CJK lists in places where users specifically want the fullwidth versions rather than the non-fullwidth.  One example where they are useful is for vertically set lists, since fullwidth characters sit upright.  Dotted decimal and parenthesised are particularly useful for vertical lists because the reduce the complexity of authoring if you want to use those styles.
1. My belief is that the fullwidth prefix is useful to distinguish from the non-fullwidth.
1. I don't want to add to just one (or to all) of CJK. Note that they may be used for Mongolian too. The current section division helps you find things quickly - ie. look under Latin for alpha, and under Digits.. for numeric templates.

Closing this. Reopen if necessary.

**Comment by Crissov** [comment]
If I understand correctly, we do agree that most (if not all) of the styles I mentioned are only supposed to be used within “fullwidth” typography, i.e. with sinographic character grid. They should not be used within documents that are primarily using a different script, the Latin/Roman one in particular. The document should reflect these recommendations. 

I still believe it’s harmful then to group them with Digit and Latin styles, respectively, because none of them is either. My point is, they’re Eastern (compatibility) characters that just happen to look like Western letters and digits (with some adornment).
